"""0001_initial_schema

Revision ID: cd7f4376ca5f
Revises: 
Create Date: 2026-03-05 05:08:53.532004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd7f4376ca5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results_cache',
    sa.Column('analysis_type', sa.String(length=60), nullable=False),
    sa.Column('upload_job_id', sa.UUID(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_cache_analysis_type'), 'analysis_results_cache', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_results_cache_computed_at'), 'analysis_results_cache', ['computed_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_cache_id'), 'analysis_results_cache', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_results_cache_is_stale'), 'analysis_results_cache', ['is_stale'], unique=False)
    op.create_index(op.f('ix_analysis_results_cache_upload_job_id'), 'analysis_results_cache', ['upload_job_id'], unique=False)
    op.create_table('csv_column_mappings',
    sa.Column('upload_job_id', sa.UUID(), nullable=False),
    sa.Column('csv_header', sa.String(length=255), nullable=False),
    sa.Column('mapped_table', sa.String(length=100), nullable=False),
    sa.Column('mapped_column', sa.String(length=100), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_method', sa.String(length=30), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_column_mappings_csv_header'), 'csv_column_mappings', ['csv_header'], unique=False)
    op.create_index(op.f('ix_csv_column_mappings_id'), 'csv_column_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_csv_column_mappings_upload_job_id'), 'csv_column_mappings', ['upload_job_id'], unique=False)
    op.create_table('customers',
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('first_purchase_date', sa.Date(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('lifetime_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('arr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ai_segment', sa.String(length=50), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('churn_risk_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('clv_predicted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cohort_month', sa.Date(), nullable=True),
    sa.Column('rfm_score', sa.String(length=10), nullable=True),
    sa.Column('rfm_segment', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_age_group'), 'customers', ['age_group'], unique=False)
    op.create_index(op.f('ix_customers_ai_segment'), 'customers', ['ai_segment'], unique=False)
    op.create_index(op.f('ix_customers_cohort_month'), 'customers', ['cohort_month'], unique=False)
    op.create_index(op.f('ix_customers_country_code'), 'customers', ['country_code'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_last_active_at'), 'customers', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_customers_lifetime_value'), 'customers', ['lifetime_value'], unique=False)
    op.create_index(op.f('ix_customers_region'), 'customers', ['region'], unique=False)
    op.create_index(op.f('ix_customers_rfm_segment'), 'customers', ['rfm_segment'], unique=False)
    op.create_table('daily_kpi_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active_customers', sa.Integer(), nullable=False),
    sa.Column('new_customers', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('churn_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('revenue_na', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue_eu', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue_apac', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue_latam', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_kpi_snapshots_id'), 'daily_kpi_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_daily_kpi_snapshots_snapshot_date'), 'daily_kpi_snapshots', ['snapshot_date'], unique=True)
    op.create_table('forecast_results',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ds', sa.Date(), nullable=False),
    sa.Column('yhat', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('yhat_lower', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('yhat_upper', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.Column('scenario_marketing_spend_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scenario_price_shift_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scenario_seasonal_adj', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_ds'), 'forecast_results', ['ds'], unique=False)
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_results_job_id'), 'forecast_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_run_date'), 'forecast_results', ['run_date'], unique=False)
    op.create_index(op.f('ix_forecast_results_user_id'), 'forecast_results', ['user_id'], unique=False)
    op.create_table('insights',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('bullet_index', sa.SmallInteger(), nullable=False),
    sa.Column('bullet_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_index(op.f('ix_insights_job_id'), 'insights', ['job_id'], unique=False)
    op.create_index(op.f('ix_insights_source_type'), 'insights', ['source_type'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('upload_job_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('acquisition_channel', sa.String(length=50), nullable=True),
    sa.Column('return_flag', sa.Boolean(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_external_id'), 'orders', ['external_id'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_region'), 'orders', ['region'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_upload_job_id'), 'orders', ['upload_job_id'], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('abc_tier', sa.String(length=1), nullable=True),
    sa.Column('abc_computed_at', sa.Date(), nullable=True),
    sa.Column('return_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_units_sold', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_abc_tier'), 'products', ['abc_tier'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_supplier'), 'products', ['supplier'], unique=False)
    op.create_index(op.f('ix_products_total_revenue'), 'products', ['total_revenue'], unique=False)
    op.create_table('upload_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_jobs_id'), 'upload_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_status'), 'upload_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_upload_jobs_user_id'), 'upload_jobs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('widget_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upload_jobs_user_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_status'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_id'), table_name='upload_jobs')
    op.drop_table('upload_jobs')
    op.drop_index(op.f('ix_products_total_revenue'), table_name='products')
    op.drop_index(op.f('ix_products_supplier'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_abc_tier'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_upload_job_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_region'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_insights_source_type'), table_name='insights')
    op.drop_index(op.f('ix_insights_job_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_forecast_results_user_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_run_date'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_job_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_ds'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_daily_kpi_snapshots_snapshot_date'), table_name='daily_kpi_snapshots')
    op.drop_index(op.f('ix_daily_kpi_snapshots_id'), table_name='daily_kpi_snapshots')
    op.drop_table('daily_kpi_snapshots')
    op.drop_index(op.f('ix_customers_rfm_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_region'), table_name='customers')
    op.drop_index(op.f('ix_customers_lifetime_value'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_active_at'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_country_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_cohort_month'), table_name='customers')
    op.drop_index(op.f('ix_customers_ai_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_age_group'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_csv_column_mappings_upload_job_id'), table_name='csv_column_mappings')
    op.drop_index(op.f('ix_csv_column_mappings_id'), table_name='csv_column_mappings')
    op.drop_index(op.f('ix_csv_column_mappings_csv_header'), table_name='csv_column_mappings')
    op.drop_table('csv_column_mappings')
    op.drop_index(op.f('ix_analysis_results_cache_upload_job_id'), table_name='analysis_results_cache')
    op.drop_index(op.f('ix_analysis_results_cache_is_stale'), table_name='analysis_results_cache')
    op.drop_index(op.f('ix_analysis_results_cache_id'), table_name='analysis_results_cache')
    op.drop_index(op.f('ix_analysis_results_cache_computed_at'), table_name='analysis_results_cache')
    op.drop_index(op.f('ix_analysis_results_cache_analysis_type'), table_name='analysis_results_cache')
    op.drop_table('analysis_results_cache')
    # ### end Alembic commands ###
