"use client";

/**
 * <AIInsightPanel> — the reserved "✨ AI Insight" slot every decision chart
 * shows beneath its visual.
 *
 * Contract (frozen now, swappable later):
 *   - Today renders the `fallback_bullets` field the analytics module emits.
 *   - Tomorrow we swap the body for an LLM call that receives the same
 *     `question + data` payload and returns the same `{ bullets: string[] }`
 *     shape. The slot, position, sizing and styling DO NOT CHANGE — the
 *     supervisor sees identical UI today and after we wire the model.
 *
 * UX rules (apply now so swap is invisible):
 *   - Exactly 3 bullets, each ≤ 140 chars, plain English, no jargon.
 *   - Disclaimer: "Generated by AI · review before acting"
 *   - Skeleton loader while pending; deterministic fallback if model fails.
 */

import { Sparkles, AlertTriangle } from "lucide-react";
import { useChartTheme } from "../chartHelpers";

export interface AIInsight {
  /** Exactly 3 bullets, each ≤ 140 chars. Owner-voice, action-oriented. */
  bullets: string[];
  /** Optional confidence band, surfaces a subtle tag in the header. */
  confidence?: "high" | "medium" | "low";
  /** ISO timestamp from the model run (or build time for fallbacks). */
  generatedAt?: string;
}

export interface AIInsightPanelProps {
  /** The analytics module key — wired later for LLM routing. */
  moduleKey: string;
  /** The owner-voice question this chart answers. */
  question?: string;
  /**
   * Analytics module output. Today we read `data.fallback_bullets`
   * (string[]). Later this will be passed verbatim to the LLM.
   */
  data: any;
  /** Show skeleton while data is in flight. */
  isLoading?: boolean;
  /** Optional className override (card chrome shouldn't need this). */
  className?: string;
}

/**
 * Coerce whatever the worker emits into the {bullets} contract.
 *
 * Accepts:
 *   - data.fallback_bullets: string[]    (preferred — current contract)
 *   - data.insight.bullets:  string[]    (forward-compatible LLM shape)
 *   - undefined / null                   (renders empty state)
 *
 * Always returns at most 3 strings, each trimmed to 140 chars.
 */
function readBullets(data: any): string[] {
  const raw: unknown =
    data?.insight?.bullets ??
    data?.fallback_bullets ??
    null;

  if (!Array.isArray(raw)) return [];
  return raw
    .filter((b): b is string => typeof b === "string" && b.trim().length > 0)
    .slice(0, 3)
    .map((b) => (b.length > 140 ? `${b.slice(0, 137)}…` : b).trim());
}

/** Tiny coloured dot used as the bullet glyph. */
function Dot({ color }: { color: string }) {
  return (
    <span
      aria-hidden
      className="inline-block w-1.5 h-1.5 rounded-full shrink-0 mt-1.5"
      style={{ background: color }}
    />
  );
}

/** Skeleton state — 3 fake bullets, used while data is loading. */
function PanelSkeleton({ border, surfaceMuted }: { border: string; surfaceMuted: string }) {
  return (
    <div
      className="rounded-lg p-3 border animate-pulse"
      style={{ borderColor: border, background: surfaceMuted }}
    >
      <div className="flex items-center gap-2 mb-2.5">
        <div className="w-4 h-4 rounded bg-slate-300/40 dark:bg-slate-600/40" />
        <div className="h-3 w-24 rounded bg-slate-300/40 dark:bg-slate-600/40" />
      </div>
      <div className="space-y-1.5">
        <div className="h-2.5 w-[92%] rounded bg-slate-300/30 dark:bg-slate-600/30" />
        <div className="h-2.5 w-[78%] rounded bg-slate-300/30 dark:bg-slate-600/30" />
        <div className="h-2.5 w-[85%] rounded bg-slate-300/30 dark:bg-slate-600/30" />
      </div>
    </div>
  );
}

export function AIInsightPanel({
  moduleKey,
  question,
  data,
  isLoading,
  className = "",
}: AIInsightPanelProps) {
  const theme = useChartTheme();

  if (isLoading) {
    return <PanelSkeleton border={theme.border} surfaceMuted={theme.surfaceMuted} />;
  }

  const bullets = readBullets(data);

  return (
    <div
      data-module={moduleKey}
      data-question={question}
      className={`rounded-lg p-3 border ${className}`}
      style={{
        borderColor: theme.border,
        background: theme.surfaceMuted,
      }}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-2 gap-2">
        <div className="flex items-center gap-1.5">
          <Sparkles className="w-3.5 h-3.5" style={{ color: theme.semantic.brand }} />
          <span
            className="text-[11px] font-bold uppercase tracking-wider"
            style={{ color: theme.semantic.brand }}
          >
            AI Insight
          </span>
        </div>
        <span
          className="text-[9px] font-medium uppercase tracking-wider whitespace-nowrap"
          style={{ color: theme.text.faint }}
        >
          Generated · review before acting
        </span>
      </div>

      {/* Bullets — or empty state if the module didn't ship any */}
      {bullets.length === 0 ? (
        <div className="flex items-start gap-2 py-1">
          <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" style={{ color: theme.text.faint }} />
          <p className="text-[11px] leading-relaxed" style={{ color: theme.text.muted }}>
            Insight will appear once enough data is collected for this chart.
          </p>
        </div>
      ) : (
        <ul className="space-y-1.5">
          {bullets.map((b, i) => (
            <li key={i} className="flex items-start gap-2">
              <Dot color={theme.semantic.brand} />
              <p
                className="text-[11.5px] leading-snug"
                style={{ color: theme.text.body }}
              >
                {b}
              </p>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
